export const POPULAR_DEGREES = [
  // Bachelor's Degrees
  "Bachelor of Science (B.Sc.)",
  "Bachelor of Arts (B.A.)",
  "Bachelor of Engineering (B.E.)",
  "Bachelor of Technology (B.Tech)",
  "Bachelor of Computer Science",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Commerce (B.Com)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Science in Nursing (BSN)",
  "Bachelor of Education (B.Ed.)",
  "Bachelor of Laws (LL.B.)",
  "Bachelor of Architecture (B.Arch)",
  "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
  "Bachelor of Pharmacy (B.Pharm)",
  "Bachelor of Design (B.Des.)",

  // Master's Degrees
  "Master of Science (M.Sc.)",
  "Master of Arts (M.A.)",
  "Master of Business Administration (MBA)",
  "Master of Engineering (M.E.)",
  "Master of Technology (M.Tech)",
  "Master of Computer Applications (MCA)",
  "Master of Fine Arts (MFA)",
  "Master of Public Health (MPH)",
  "Master of Education (M.Ed.)",
  "Master of Laws (LL.M.)",
  "Master of Social Work (MSW)",
  "Master of Architecture (M.Arch)",
  "Master of Public Administration (MPA)",
  "Master of Finance (M.Fin.)",
  "Master of Data Science",

  // Doctoral Degrees
  "Doctor of Philosophy (Ph.D.)",
  "Doctor of Medicine (M.D.)",
  "Doctor of Education (Ed.D.)",
  "Doctor of Business Administration (DBA)",
  "Doctor of Pharmacy (Pharm.D.)",
  "Juris Doctor (J.D.)",

  // Diplomas & Certificates
  "Diploma in Engineering",
  "Diploma in Computer Applications",
  "Post Graduate Diploma in Management (PGDM)",
  "Advanced Diploma",
  "Professional Certificate",

  // Specialized Fields
  "Computer Science",
  "Information Technology",
  "Software Engineering",
  "Data Science",
  "Artificial Intelligence",
  "Cybersecurity",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Environmental Engineering",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "Human Resources Management",
  "Psychology",
  "Sociology",
  "Political Science",
  "International Relations",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Biotechnology",
  "Graphic Design",
  "Interior Design",
  "Fashion Design",
  "Communications",
  "Journalism",
  "Mass Media",
];
