export const POPULAR_HOBBIES = [
  "Photography",
  "Chess",
  "Traveling",
  "Reading",
  "Hiking",
  "Cooking",
  "Gaming",
  "Singing",
  "Dancing",
  "Painting",
  "Sketching",
  "Gardening",
  "Swimming",
  "Running",
  "Cycling",
  "Yoga",
  "Meditation",
  "Writing",
  "Blogging",
  "Volunteering",
  "Open Source Contributing",
  "Mentoring",
  "Public Speaking",
  "Learning New Languages",
  "Playing Musical Instruments",
  "Watching Movies",
  "Listening to Podcasts",
  "Astrophysics",
  "Robotics",
  "Artificial Intelligence",
  "Drones",
  "3D Printing",
  "Woodworking",
  "Pottery",
  "Stargazing",
  "Fishing",
  "Scuba Diving",
  "Surfing",
  "Skiing",
  "Snowboarding",
];
