export const POPULAR_SKILLS = [
  // Programming Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Scala",
  "R",
  "MATLAB",
  "Perl",
  "Shell Scripting",
  "Bash",

  // Web Development
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Next.js",
  "Nuxt.js",
  "HTML5",
  "CSS3",
  "SASS/SCSS",
  "Tailwind CSS",
  "Bootstrap",
  "jQuery",
  "Redux",
  "GraphQL",
  "REST API",
  "WebSockets",

  // Mobile Development
  "React Native",
  "Flutter",
  "Android Development",
  "iOS Development",
  "Xamarin",
  "Ionic",

  // Backend & Databases
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Firebase",
  "Supabase",
  "Oracle",
  "Cassandra",
  "DynamoDB",
  "SQLite",

  // Cloud & DevOps
  "AWS",
  "Azure",
  "Google Cloud Platform (GCP)",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "CI/CD",
  "Terraform",
  "Ansible",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Linux",
  "Shell Scripting",

  // Data Science & AI
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Data Analysis",
  "Data Visualization",
  "Tableau",
  "Power BI",
  "NLP",
  "Computer Vision",
  "Neural Networks",

  // Testing & Quality
  "Jest",
  "Mocha",
  "Cypress",
  "Selenium",
  "Unit Testing",
  "Integration Testing",
  "Test Automation",
  "Quality Assurance (QA)",

  // Design & Creative
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "InDesign",
  "Wireframing",
  "Prototyping",
  "Graphic Design",
  "Web Design",
  "User Research",

  // Soft Skills
  "Communication",
  "Leadership",
  "Team Collaboration",
  "Problem Solving",
  "Critical Thinking",
  "Time Management",
  "Project Management",
  "Agile Methodology",
  "Scrum",
  "Kanban",
  "Stakeholder Management",
  "Conflict Resolution",
  "Negotiation",
  "Public Speaking",
  "Presentation Skills",
  "Adaptability",
  "Decision Making",
  "Creativity",
  "Attention to Detail",
  "Work Ethic",
  "Customer Service",
  "Sales",
  "Marketing",
  "Business Analysis",
  "Strategic Planning",

  // Office & Productivity
  "Microsoft Office",
  "Microsoft Excel",
  "Microsoft Word",
  "Microsoft PowerPoint",
  "Google Workspace",
  "Slack",
  "Trello",
  "Jira",
  "Asana",
  "Notion",
  "Confluence",

  // Other Technical Skills
  "Microservices",
  "System Design",
  "API Development",
  "API Integration",
  "Blockchain",
  "Cybersecurity",
  "Network Security",
  "Penetration Testing",
  "Ethical Hacking",
  "Cloud Architecture",
  "Data Structures",
  "Algorithms",
  "Object-Oriented Programming (OOP)",
  "Functional Programming",
  "Version Control",
  "Debugging",
  "Performance Optimization",
  "Code Review",
  "Technical Documentation",
  "Troubleshooting",
  "System Administration",
];
